language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install mosquitto

before_script:
  - service mosquitto start
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-mqtt/build_config.rb .

script: 
  - make all test
